### ISSUE TITLE
当前客户端版本过低，请前往应用商店升级到最新版本客户端后再登录

### ISSUE THREAD

**Issue by Wenbobobo** [duo/octopus-wechat#2]
![image](https://github.com/duo/octopus-wechat/assets/78262508/0cef52ec-f9d3-415a-93e4-5d22a2af55c3)
平常个把月要重新登陆一次，但昨天登陆后发现弹出这个，不给登录。
点击确定后过几秒就关闭vnc了

**Comment by Wenbobobo** [comment]
搜了一下似乎能直接改，不用升级。但咱不清楚是否有办法在里面运行个CE或脚本
https://blog.csdn.net/Scoful/article/details/139330910

**Comment by Wenbobobo** [comment]
在另一个地方问了

**Comment by linep47** [comment]
> 在另一个地方问了

你好，请问是怎么解决的

**Comment by Wenbobobo** [comment]
> > 在另一个地方问了
> 
> 你好，请问是怎么解决的

是在octopus那边开了个issue（
现在的解决方案是：
调用下 comwechat 的 api，curl 命令是这个：

curl -X POST 'http://127.0.0.1:18888/api/?type=35' -d '{"version": "3.9.12.16"}'

版本号奇数位是x64版本，偶数位是x86
